sudo snap install spotify
sudo snap install eclipse 
sudo snap install android-studio 
sudo snap install pycharm-community 
sudo snap install intellij-idea-community
sudo snap install rubymine 
sudo snap install notepadqq 
sudo snap install skype 
sudo snap install vlc 
sudo snap install chromium 
sudo snap install simplenote-jamiebennett
